title: Le journal intime
email: 
description: >
  Journal , <br>
  Par Mr. P. Marat auteur de l'Offrande a la patrie, <br>
  du Moniteur et du Plan de Constitution, etc.
tagline: vitam impendere vero
date: true
baseurl: "/ordinaryday" # the subpath of your site, e.g. /blog
url: "http://vyej.github.io" # the base hostname & protocol for your site, e.g. http://example.com

