name: Ordinary Days
url: https://vyej.github.io/ordinaryday
description: It is a Diary!

permalink: /:year/:month/:day/:title/
paginate: 7

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
