title: Le journal intime
email: 
description: >
  Gewahrnis Endlichkeit Anwesen - Lassen, sich ereignen Journal , <br>
  Les plus grandes idees de la divinite nous viennent par la ...  <br>
  deus sive casus, Andenken , Dichterphilosoph Vorfrage , etc.
tagline: vitam impendere vero
date: true
baseurl: "/ordinaryday" # the subpath of your site, e.g. /blog
url: "http://vyej.github.io" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 10
paginate_path: '/page:num/'

permalink: /:year/:month/:day/

# Build settings
markdown: kramdown
plugins:
  - github-pages
